### ISSUE TITLE
Image with alt text are sometimes not displayed

### ISSUE THREAD

**Issue by kangruixiang** [ozntel/oz-image-in-editor-obsidian#56]
It's odd. Some images with alt texts are not displayed at all.

1st link: image does not appear
2nd link, take away the last 2 letters in alt text: image appears
3rd link, add letter: image appears
https://i.imgur.com/RWyU7K2.png

**Comment by ozntel** [comment]
New release should solve the issue. kindly update the plugin.

**Comment by kangruixiang** [comment]
Hello, thank you for the update. It fixed that specific scenario but sadly did not fix this scenario:

![image](https://user-images.githubusercontent.com/17035138/131747684-c9e1c727-2e8a-4307-b00e-80d587b481b5.png)
